name: roll_dice_2d
description: A roll dice 2D package.
version: 1.0.2
repository: https://github.com/4rthurmonteiro/roll_dice_2d
issue_tracker: https://github.com/4rthurmonteiro/roll_dice_2d/issues

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  sonar_analysis: ^2.0.1

flutter:
  assets:
    - assets/images/

topics:
  - dice
  - game
  